In [ ]:
from agna_market_api.agmarknet_api import fetch_current_prices
from agna_market_api.agmarknet_api import fetch_historical_prices
from agna_market_api.agmarknet_api import sync_all_commodities

In [77]:
import json
import pandas as pd
import numpy as np

In [78]:
sync_all_commodities()

Syncing daily mandi prices for Tomato in Andhra Pradesh...
Raw API records fetched: 10
Rows synced for your six commodities: 10

==================================================

Syncing daily mandi prices for Onion in Andhra Pradesh...
No API data found for Onion in Andhra Pradesh.

==================================================

Syncing daily mandi prices for Potato in Andhra Pradesh...
Raw API records fetched: 1
Rows synced for your six commodities: 1

==================================================

Syncing daily mandi prices for Cauliflower in Andhra Pradesh...
Raw API records fetched: 1
Rows synced for your six commodities: 1

==================================================

Syncing daily mandi prices for Brinjal in Andhra Pradesh...
Raw API records fetched: 1
Rows synced for your six commodities: 1

==================================================

Syncing daily mandi prices for Green Chilli in Andhra Pradesh...
Raw API records fetched: 1
Rows synced for your six commodities: 1

==================================================

In [79]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("./database/mandi_prices.db")


u_query = """
SELECT *
FROM mandi_market_data
WHERE arrival_date = ?
"""
history_7 = pd.read_sql_query(
    u_query,
    conn,
    params=['2026-07-10']
)

conn.close()

In [80]:
pd.DataFrame(history_7)

,state,district,market,commodity_group,commodity,variety,grade,min_price,max_price,modal_price,price_unit,arrival_quantity,arrival_unit,arrival_date
0,Andhra Pradesh,Annamayya,B.Kothakota H/Q Angallu,Vegetables,Tomato,Local,FAQ,1000.0,1700.0,1300.0,Rs./Quintal,None,None,2026-07-10
1,Andhra Pradesh,Annamayya,Guramkonda Sub-yard of AMC Valmikipuram,Vegetables,Tomato,Hybrid,FAQ,1040.0,1400.0,1200.0,Rs./Quintal,None,None,2026-07-10
2,Andhra Pradesh,Annamayya,Kalikiri APMC,Vegetables,Tomato,Hybrid,FAQ,1000.0,1600.0,1300.0,Rs./Quintal,None,None,2026-07-10
3,Andhra Pradesh,Annamayya,Madanapalli APMC,Vegetables,Tomato,Local,FAQ,1500.0,1900.0,1800.0,Rs./Quintal,None,None,2026-07-10
4,Andhra Pradesh,Annamayya,Mulakalacheruvu APMC,Vegetables,Tomato,Local,FAQ,900.0,1850.0,1450.0,Rs./Quintal,None,None,2026-07-10
5,Andhra Pradesh,Annamayya,Punganur APMC,Vegetables,Tomato,Hybrid,FAQ,1200.0,1800.0,1600.0,Rs./Quintal,None,None,2026-07-10
6,Andhra Pradesh,Annamayya,Somala APMC,Vegetables,Tomato,Tomato,FAQ,1000.0,1400.0,1200.0,Rs./Quintal,None,None,2026-07-10
7,Andhra Pradesh,Annamayya,Valmikipuram APMC,Vegetables,Tomato,Hybrid,FAQ,1040.0,1400.0,1200.0,Rs./Quintal,None,None,2026-07-10
8,Andhra Pradesh,Chittor,Palamaner APMC,Vegetables,Brinjal,Brinjal,FAQ,3000.0,5000.0,4000.0,Rs./Quintal,None,None,2026-07-10
9,Andhra Pradesh,Chittor,Palamaner APMC,Vegetables,Cauliflower,Cauliflower,FAQ,1100.0,1500.0,1300.0,Rs./Quintal,None,None,2026-07-10
10,Andhra Pradesh,Chittor,Palamaner APMC,Vegetables,Green Chilli,Green Chilly,FAQ,3000.0,4000.0,3500.0,Rs./Quintal,None,None,2026-07-10
11,Andhra Pradesh,Chittor,Palamaner APMC,Vegetables,Potato,Potato,FAQ,1400.0,2000.0,1600.0,Rs./Quintal,None,None,2026-07-10
12,Andhra Pradesh,Chittor,Palamaner APMC,Vegetables,Tomato,Tomato,FAQ,1200.0,1800.0,1600.0,Rs./Quintal,None,None,2026-07-10
13,Andhra Pradesh,Chittor,V. Kota Sub-yard of AMC Palamaneru,Vegetables,Tomato,Other,FAQ,1200.0,1600.0,1400.0,Rs./Quintal,None,None,2026-07-10

In [81]:
commodity = 'Potato'
state = 'Andhra Pradesh'
market_name = 'Palamaner APMC'

In [82]:
historic_prices = fetch_historical_prices(commodity=commodity,state=state, market=market_name)

In [83]:
historic_prices

,arrival_date,state,district,market,commodity_group,commodity,variety,grade,min_price,max_price,modal_price,price_unit,arrival_quantity,arrival_unit
0,2026-07-04,Andhra Pradesh,Chittor,Palamaner APMC,Vegetables,Potato,Potato,FAQ,1400.0,2000.0,1800.0,Rs./Quintal,1.9,Metric Tonnes
1,2026-07-05,Andhra Pradesh,Chittor,Palamaner APMC,Vegetables,Potato,Potato,FAQ,1400.0,2000.0,1600.0,Rs./Quintal,2.2,Metric Tonnes
2,2026-07-06,Andhra Pradesh,Chittor,Palamaner APMC,Vegetables,Potato,Potato,FAQ,1400.0,2000.0,1600.0,Rs./Quintal,7.6,Metric Tonnes
3,2026-07-07,Andhra Pradesh,Chittor,Palamaner APMC,Vegetables,Potato,Potato,FAQ,1400.0,2000.0,1600.0,Rs./Quintal,2.1,Metric Tonnes
4,2026-07-08,Andhra Pradesh,Chittor,Palamaner APMC,Vegetables,Potato,Potato,FAQ,1400.0,2000.0,1600.0,Rs./Quintal,2.3,Metric Tonnes
5,2026-07-09,Andhra Pradesh,Chittor,Palamaner APMC,Vegetables,Potato,Potato,FAQ,1400.0,2000.0,1600.0,Rs./Quintal,NaN,None
6,2026-07-10,Andhra Pradesh,Chittor,Palamaner APMC,Vegetables,Potato,Potato,FAQ,1400.0,2000.0,1600.0,Rs./Quintal,NaN,None

In [84]:
import json
import pprint

file_path = r"../crop_database/crop_knowledge_base.json"

with open(file_path, "r", encoding="utf-8") as file:
    data = json.load(file)

print(pprint.pp(data[f'{commodity.lower()}']))

crop_knowledge = data[f'{commodity.lower()}']

{'crop_name': 'Potato',
 'optimal_temp_range_c': [15, 20],
 'critical_temp_max_c': 26.6,
 'critical_temp_min_c': 2,
 'chilling_injury_threshold_c': None,
 'frost_sensitive': True,
 'heat_sensitive': False,
 'rain_sensitive': True,
 'waterlogging_sensitive': True,
 'rain_risk_mm_threshold': 20,
 'storage_life_days': 180,
 'storage_temp_by_use_c': {'seed': [2.0, 4.0],
                           'table_fresh': [4.0, 7.0],
                           'processing_chips_fries': [8.0, 10.0]},
 'perishability': 'medium',
 'harvest_window_days': 7,
 'field_lifecycle_days': [90, 120],
 'price_volatility': 'medium',
 'sell_or_wait_bias': 'can_wait_for_better_price',
 'grading_note': 'Grades: Super, Grade-A, Grade-B. Large/Super: over 65mm '
                 'diameter. Medium/Grade A: 46-65mm. Small/Grade B: 35-45mm. '
                 'Processing buyers require 20-25% dry matter content; low dry '
                 'matter causes excess oil absorption and disintegration when '
                 'fried.',
 'advisory_note': 'Storage temperature determines end-use suitability: table '
                  'potatoes stored at 4-7C develop cold-induced sweetening '
                  '(starch converts to sugar) and are unsuitable for '
                  'processing/frying, which requires warmer 8-10C storage to '
                  'avoid dark, bitter fries. Do not advise selling cold-stored '
                  'table potatoes to processing buyers during a price crash in '
                  'the table market; they will likely be rejected at the '
                  'processing gate. Table potatoes have roughly a 6-month '
                  'shelf life, so holding until the table market recovers is '
                  'often viable. Rain and cool, humid conditions favor late '
                  'blight; waterlogging during tuber initiation (35-45 days) '
                  'or bulking (60-75 days) is especially damaging.'}
None

In [85]:
from weather_api.weather_api import fetch_weather_data

In [86]:
# Madanapalle Area
latitude = 13.552040
longitude = 78.505798

In [87]:
data = fetch_weather_data(latitude=latitude, longitude=longitude)

In [88]:
data_weather = data
pprint.pp(data_weather)

{'cod': '200',
 'message': 0,
 'cnt': 40,
 'list': [{'dt': 1783695600,
           'main': {'temp': 28.97,
                    'feels_like': 30.13,
                    'temp_min': 28.55,
                    'temp_max': 28.97,
                    'pressure': 1010,
                    'sea_level': 1010,
                    'grnd_level': 926,
                    'humidity': 54,
                    'temp_kf': 0.42,
                    'dew_point': 18.73},
           'weather': [{'id': 804,
                        'main': 'Clouds',
                        'description': 'overcast clouds',
                        'icon': '04n'}],
           'clouds': {'all': 100},
           'wind': {'speed': 4.13, 'deg': 286, 'gust': 7.67},
           'visibility': 10000,
           'pop': 0,
           'sys': {'pod': 'n'},
           'dt_txt': '2026-07-10 15:00:00'},
          {'dt': 1783706400,
           'main': {'temp': 27.52,
                    'feels_like': 28.77,
                    'temp_min': 26.69,
                    'temp_max': 27.52,
                    'pressure': 1010,
                    'sea_level': 1010,
                    'grnd_level': 926,
                    'humidity': 60,
                    'temp_kf': 0.83,
                    'dew_point': 19.06},
           'weather': [{'id': 804,
                        'main': 'Clouds',
                        'description': 'overcast clouds',
                        'icon': '04n'}],
           'clouds': {'all': 95},
           'wind': {'speed': 6.4, 'deg': 284, 'gust': 9.97},
           'visibility': 10000,
           'pop': 0,
           'sys': {'pod': 'n'},
           'dt_txt': '2026-07-10 18:00:00'},
          {'dt': 1783717200,
           'main': {'temp': 23.73,
                    'feels_like': 24.06,
                    'temp_min': 23.73,
                    'temp_max': 23.73,
                    'pressure': 1009,
                    'sea_level': 1009,
                    'grnd_level': 924,
                    'humidity': 73,
                    'temp_kf': 0,
                    'dew_point': 18.59},
           'weather': [{'id': 804,
                        'main': 'Clouds',
                        'description': 'overcast clouds',
                        'icon': '04n'}],
           'clouds': {'all': 100},
           'wind': {'speed': 6.59, 'deg': 270, 'gust': 12.6},
           'visibility': 10000,
           'pop': 0,
           'sys': {'pod': 'n'},
           'dt_txt': '2026-07-10 21:00:00'},
          {'dt': 1783728000,
           'main': {'temp': 22.68,
                    'feels_like': 23.01,
                    'temp_min': 22.68,
                    'temp_max': 22.68,
                    'pressure': 1010,
                    'sea_level': 1010,
                    'grnd_level': 924,
                    'humidity': 77,
                    'temp_kf': 0,
                    'dew_point': 18.6},
           'weather': [{'id': 804,
                        'main': 'Clouds',
                        'description': 'overcast clouds',
                        'icon': '04n'}],
           'clouds': {'all': 100},
           'wind': {'speed': 6.81, 'deg': 277, 'gust': 13.57},
           'visibility': 10000,
           'pop': 0,
           'sys': {'pod': 'n'},
           'dt_txt': '2026-07-11 00:00:00'},
          {'dt': 1783738800,
           'main': {'temp': 25.31,
                    'feels_like': 25.59,
                    'temp_min': 25.31,
                    'temp_max': 25.31,
                    'pressure': 1011,
                    'sea_level': 1011,
                    'grnd_level': 926,
                    'humidity': 65,
                    'temp_kf': 0,
                    'dew_point': 18.33},
           'weather': [{'id': 804,
                        'main': 'Clouds',
                        'description': 'overcast clouds',
                        'icon': '04d'}],
           'clouds': {'all': 98},
           'wind': {'speed': 8.77, 'deg': 287, 'gust': 12.57},
           'visibility': 10000,
           'pop': 0,
           'sys': {'pod': 'd'},
           'dt_txt': '2026-07-11 03:00:00'},
          {'dt': 1783749600,
           'main': {'temp': 28.97,
                    'feels_like': 29.27,
                    'temp_min': 28.97,
                    'temp_max': 28.97,
                    'pressure': 1010,
                    'sea_level': 1010,
                    'grnd_level': 925,
                    'humidity': 47,
                    'temp_kf': 0,
                    'dew_point': 17.27},
           'weather': [{'id': 804,
                        'main': 'Clouds',
                        'description': 'overcast clouds',
                        'icon': '04d'}],
           'clouds': {'all': 96},
           'wind': {'speed': 8.84, 'deg': 288, 'gust': 10.55},
           'visibility': 10000,
           'pop': 0,
           'sys': {'pod': 'd'},
           'dt_txt': '2026-07-11 06:00:00'},
          {'dt': 1783760400,
           'main': {'temp': 30.69,
                    'feels_like': 30.02,
                    'temp_min': 30.69,
                    'temp_max': 30.69,
                    'pressure': 1007,
                    'sea_level': 1007,
                    'grnd_level': 923,
                    'humidity': 36,
                    'temp_kf': 0,
                    'dew_point': 15.37},
           'weather': [{'id': 804,
                        'main': 'Clouds',
                        'description': 'overcast clouds',
                        'icon': '04d'}],
           'clouds': {'all': 100},
           'wind': {'speed': 8.49, 'deg': 285, 'gust': 9.57},
           'visibility': 10000,
           'pop': 0,
           'sys': {'pod': 'd'},
           'dt_txt': '2026-07-11 09:00:00'},
          {'dt': 1783771200,
           'main': {'temp': 31.23,
                    'feels_like': 31.07,
                    'temp_min': 31.23,
                    'temp_max': 31.23,
                    'pressure': 1007,
                    'sea_level': 1007,
                    'grnd_level': 923,
                    'humidity': 39,
                    'temp_kf': 0,
                    'dew_point': 15.68},
           'weather': [{'id': 804,
                        'main': 'Clouds',
                        'description': 'overcast clouds',
                        'icon': '04d'}],
           'clouds': {'all': 100},
           'wind': {'speed': 7.61, 'deg': 278, 'gust': 9.14},
           'visibility': 10000,
           'pop': 0,
           'sys': {'pod': 'd'},
           'dt_txt': '2026-07-11 12:00:00'},
          {'dt': 1783782000,
           'main': {'temp': 28.81,
                    'feels_like': 29.77,
                    'temp_min': 28.81,
                    'temp_max': 28.81,
                    'pressure': 1009,
                    'sea_level': 1009,
                    'grnd_level': 925,
                    'humidity': 53,
                    'temp_kf': 0,
                    'dew_point': 17.4},
           'weather': [{'id': 804,
                        'main': 'Clouds',
                        'description': 'overcast clouds',
                        'icon': '04n'}],
           'clouds': {'all': 100},
           'wind': {'speed': 6.86, 'deg': 281, 'gust': 10.55},
           'visibility': 10000,
           'pop': 0,
           'sys': {'pod': 'n'},
           'dt_txt': '2026-07-11 15:00:00'},
          {'dt': 1783792800,
           'main': {'temp': 26.35,
                    'feels_like': 26.35,
                    'temp_min': 26.35,
                    'temp_max': 26.35,
                    'pressure': 1010,
                    'sea_level': 1010,
                    'grnd_level': 925,
                    'humidity': 62,
                    'temp_kf': 0,
                    'dew_point': 17.8},
           'weather': [{'id': 804,
                        'main': 'Clouds',
                        'description': 'overcast clouds',
                        'icon': '04n'}],
           'clouds': {'all': 100},
           'wind': {'speed': 6.73, 'deg': 279, 'gust': 11.77},
           'visibility': 10000,
           'pop': 0,
           'sys': {'pod': 'n'},
           'dt_txt': '2026-07-11 18:00:00'},
          {'dt': 1783803600,
           'main': {'temp': 23.84,
                    'feels_like': 24.06,
                    'temp_min': 23.84,
                    'temp_max': 23.84,
                    'pressure': 1008,
                    'sea_level': 1008,
                    'grnd_level': 923,
                    'humidity': 68,
                    'temp_kf': 0,
                    'dew_point': 17.55},
           'weather': [{'id': 804,
                        'main': 'Clouds',
                        'description': 'overcast clouds',
                        'icon': '04n'}],
           'clouds': {'all': 100},
           'wind': {'speed': 5.58, 'deg': 272, 'gust': 12.09},
           'visibility': 10000,
           'pop': 0,
           'sys': {'pod': 'n'},
           'dt_txt': '2026-07-11 21:00:00'},
          {'dt': 1783814400,
           'main': {'temp': 22.76,
                    'feels_like': 23,
                    'temp_min': 22.76,
                    'temp_max': 22.76,
                    'pressure': 1008,
                    'sea_level': 1008,
                    'grnd_level': 923,
                    'humidity': 73,
                    'temp_kf': 0,
                    'dew_point': 17.78},
           'weather': [{'id': 804,
                        'main': 'Clouds',
                        'description': 'overcast clouds',
                        'icon': '04n'}],
           'clouds': {'all': 100},
           'wind': {'speed': 4.92, 'deg': 271, 'gust': 12.1},
           'visibility': 10000,
           'pop': 0,
           'sys': {'pod': 'n'},
           'dt_txt': '2026-07-12 00:00:00'},
          {'dt': 1783825200,
           'main': {'temp': 25.3,
                    'feels_like': 25.48,
                    'temp_min': 25.3,
                    'temp_max': 25.3,
                    'pressure': 1010,
                    'sea_level': 1010,
                    'grnd_level': 924,
                    'humidity': 61,
                    'temp_kf': 0,
                    'dew_point': 17.27},
           'weather': [{'id': 804,
                        'main': 'Clouds',
                        'description': 'overcast clouds',
                        'icon': '04d'}],
           'clouds': {'all': 94},
           'wind': {'speed': 7.42, 'deg': 275, 'gust': 10.7},
           'visibility': 10000,
           'pop': 0,
           'sys': {'pod': 'd'},
           'dt_txt': '2026-07-12 03:00:00'},
          {'dt': 1783836000,
           'main': {'temp': 29.1,
                    'feels_like': 28.62,
                    'temp_min': 29.1,
                    'temp_max': 29.1,
                    'pressure': 1008,
                    'sea_level': 1008,
                    'grnd_level': 924,
                    'humidity': 39,
                    'temp_kf': 0,
                    'dew_point': 15.02},
           'weather': [{'id': 804,
                        'main': 'Clouds',
                        'description': 'overcast clouds',
                        'icon': '04d'}],
           'clouds': {'all': 97},
           'wind': {'speed': 8.13, 'deg': 286, 'gust': 9.9},
           'visibility': 10000,
           'pop': 0,
           'sys': {'pod': 'd'},
           'dt_txt': '2026-07-12 06:00:00'},
          {'dt': 1783846800,
           'main': {'temp': 32.38,
                    'feels_like': 31.38,
                    'temp_min': 32.38,
                    'temp_max': 32.38,
                    'pressure': 1006,
                    'sea_level': 1006,
                    'grnd_level': 922,
                    'humidity': 31,
                    'temp_kf': 0,
                    'dew_point': 13.56},
           'weather': [{'id': 804,
                        'main': 'Clouds',
                        'description': 'overcast clouds',
                        'icon': '04d'}],
           'clouds': {'all': 100},
           'wind': {'speed': 9.01, 'deg': 292, 'gust': 10.41},
           'visibility': 10000,
           'pop': 0,
           'sys': {'pod': 'd'},
           'dt_txt': '2026-07-12 09:00:00'},
          {'dt': 1783857600,
           'main': {'temp': 31.13,
                    'feels_like': 30.66,
                    'temp_min': 31.13,
                    'temp_max': 31.13,
                    'pressure': 1006,
                    'sea_level': 1006,
                    'grnd_level': 922,
                    'humidity': 37,
                    'temp_kf': 0,
                    'dew_point': 14.78},
           'weather': [{'id': 804,
                        'main': 'Clouds',
                        'description': 'overcast clouds',
                        'icon': '04d'}],
           'clouds': {'all': 100},
           'wind': {'speed': 8.21, 'deg': 292, 'gust': 10.18},
           'visibility': 10000,
           'pop': 0,
           'sys': {'pod': 'd'},
           'dt_txt': '2026-07-12 12:00:00'},
          {'dt': 1783868400,
           'main': {'temp': 26.77,
                    'feels_like': 27.37,
                    'temp_min': 26.77,
                    'temp_max': 26.77,
                    'pressure': 1009,
                    'sea_level': 1009,
                    'grnd_level': 924,
                    'humidity': 53,
                    'temp_kf': 0,
                    'dew_point': 16.43},
           'weather': [{'id': 804,
                        'main': 'Clouds',
                        'description': 'overcast clouds',
                        'icon': '04n'}],
           'clouds': {'all': 100},
           'wind': {'speed': 8.19, 'deg': 285, 'gust': 11.89},
           'visibility': 10000,
           'pop': 0,
           'sys': {'pod': 'n'},
           'dt_txt': '2026-07-12 15:00:00'},
          {'dt': 1783879200,
           'main': {'temp': 24.42,
                    'feels_like': 24.59,
                    'temp_min': 24.42,
                    'temp_max': 24.42,
                    'pressure': 1010,
                    'sea_level': 1010,
                    'grnd_level': 925,
                    'humidity': 64,
                    'temp_kf': 0,
                    'dew_point': 17.11},
           'weather': [{'id': 804,
                        'main': 'Clouds',
                        'description': 'overcast clouds',
                        'icon': '04n'}],
           'clouds': {'all': 100},
           'wind': {'speed': 7.61, 'deg': 281, 'gust': 13.18},
           'visibility': 10000,
           'pop': 0,
           'sys': {'pod': 'n'},
           'dt_txt': '2026-07-12 18:00:00'},
          {'dt': 1783890000,
           'main': {'temp': 22.85,
                    'feels_like': 23.04,
                    'temp_min': 22.85,
                    'temp_max': 22.85,
                    'pressure': 1008,
                    'sea_level': 1008,
                    'grnd_level': 923,
                    'humidity': 71,
                    'temp_kf': 0,
                    'dew_point': 17.45},
           'weather': [{'id': 804,
                        'main': 'Clouds',
                        'description': 'overcast clouds',
                        'icon': '04n'}],
           'clouds': {'all': 100},
           'wind': {'speed': 8.17, 'deg': 284, 'gust': 14.87},
           'visibility': 10000,
           'pop': 0,
           'sys': {'pod': 'n'},
           'dt_txt': '2026-07-12 21:00:00'},
          {'dt': 1783900800,
           'main': {'temp': 22.46,
                    'feels_like': 22.67,
                    'temp_min': 22.46,
                    'temp_max': 22.46,
                    'pressure': 1008,
                    'sea_level': 1008,
                    'grnd_level': 923,
                    'humidity': 73,
                    'temp_kf': 0,
                    'dew_point': 17.36},
           'weather': [{'id': 804,
                        'main': 'Clouds',
                        'description': 'overcast clouds',
                        'icon': '04n'}],
           'clouds': {'all': 100},
           'wind': {'speed': 7.42, 'deg': 285, 'gust': 15.21},
           'visibility': 10000,
           'pop': 0,
           'sys': {'pod': 'n'},
           'dt_txt': '2026-07-13 00:00:00'},
          {'dt': 1783911600,
           'main': {'temp': 25.11,
                    'feels_like': 25.16,
                    'temp_min': 25.11,
                    'temp_max': 25.11,
                    'pressure': 1010,
                    'sea_level': 1010,
                    'grnd_level': 924,
                    'humidity': 57,
                    'temp_kf': 0,
                    'dew_point': 15.96},
           'weather': [{'id': 804,
                        'main': 'Clouds',
                        'description': 'overcast clouds',
                        'icon': '04d'}],
           'clouds': {'all': 98},
           'wind': {'speed': 9.34, 'deg': 289, 'gust': 13.83},
           'visibility': 10000,
           'pop': 0,
           'sys': {'pod': 'd'},
           'dt_txt': '2026-07-13 03:00:00'},
          {'dt': 1783922400,
           'main': {'temp': 30.46,
                    'feels_like': 29.65,
                    'temp_min': 30.46,
                    'temp_max': 30.46,
                    'pressure': 1008,
                    'sea_level': 1008,
                    'grnd_level': 924,
                    'humidity': 35,
                    'temp_kf': 0,
                    'dew_point': 13.51},
           'weather': [{'id': 804,
                        'main': 'Clouds',
                        'description': 'overcast clouds',
                        'icon': '04d'}],
           'clouds': {'all': 99},
           'wind': {'speed': 9.59, 'deg': 292, 'gust': 11.51},
           'visibility': 10000,
           'pop': 0,
           'sys': {'pod': 'd'},
           'dt_txt': '2026-07-13 06:00:00'},
          {'dt': 1783933200,
           'main': {'temp': 33.74,
                    'feels_like': 32.35,
                    'temp_min': 33.74,
                    'temp_max': 33.74,
                    'pressure': 1005,
                    'sea_level': 1005,
                    'grnd_level': 921,
                    'humidity': 26,
                    'temp_kf': 0,
                    'dew_point': 11.9},
           'weather': [{'id': 804,
                        'main': 'Clouds',
                        'description': 'overcast clouds',
                        'icon': '04d'}],
           'clouds': {'all': 100},
           'wind': {'speed': 9.11, 'deg': 299, 'gust': 10.58},
           'visibility': 10000,
           'pop': 0,
           'sys': {'pod': 'd'},
           'dt_txt': '2026-07-13 09:00:00'},
          {'dt': 1783944000,
           'main': {'temp': 32.85,
                    'feels_like': 31.55,
                    'temp_min': 32.85,
                    'temp_max': 32.85,
                    'pressure': 1005,
                    'sea_level': 1005,
                    'grnd_level': 921,
                    'humidity': 28,
                    'temp_kf': 0,
                    'dew_point': 12.42},
           'weather': [{'id': 804,
                        'main': 'Clouds',
                        'description': 'overcast clouds',
                        'icon': '04d'}],
           'clouds': {'all': 100},
           'wind': {'speed': 7.68, 'deg': 299, 'gust': 9.84},
           'visibility': 10000,
           'pop': 0,
           'sys': {'pod': 'd'},
           'dt_txt': '2026-07-13 12:00:00'},
          {'dt': 1783954800,
           'main': {'temp': 29.06,
                    'feels_like': 28.67,
                    'temp_min': 29.06,
                    'temp_max': 29.06,
                    'pressure': 1008,
                    'sea_level': 1008,
                    'grnd_level': 924,
                    'humidity': 40,
                    'temp_kf': 0,
                    'dew_point': 14.17},
           'weather': [{'id': 804,

In [89]:
def safe_float(value, default=None):
    """Convert values including NaN into JSON-safe floats."""
    if value is None or pd.isna(value):
        return default
    return float(value)

In [90]:
def summarize_market(history: pd.DataFrame) -> dict:
    """
    history must contain:
    arrival_date, state, district, market, commodity,
    min_price, max_price, modal_price, price_unit
    """
    if history is None or history.empty:
        return {
            "available": False,
            "message": "No market-price records found."
        }

    df = history.copy()

    df["arrival_date"] = pd.to_datetime(df["arrival_date"], errors="coerce")
    df["modal_price"] = pd.to_numeric(df["modal_price"], errors="coerce")
    df["min_price"] = pd.to_numeric(df["min_price"], errors="coerce")
    df["max_price"] = pd.to_numeric(df["max_price"], errors="coerce")

    df = (
        df.dropna(subset=["arrival_date", "modal_price"])
          .sort_values("arrival_date")
          .drop_duplicates(subset=["arrival_date"], keep="last")
          .tail(7)
          .reset_index(drop=True)
    )

    if df.empty:
        return {
            "available": False,
            "message": "No valid market-price records found."
        }

    first = df.iloc[0]
    latest = df.iloc[-1]
    previous = df.iloc[-2] if len(df) >= 2 else None

    avg_price = float(df["modal_price"].mean())
    first_price = float(first["modal_price"])
    latest_price = float(latest["modal_price"])

    seven_day_change = (
        ((latest_price - first_price) / first_price) * 100
        if first_price != 0 else None
    )

    previous_price = float(previous["modal_price"]) if previous is not None else None
    day_change = (
        ((latest_price - previous_price) / previous_price) * 100
        if previous_price not in (None, 0) else None
    )

    # Small fluctuations should not be labeled rising/falling.
    if seven_day_change is None or abs(seven_day_change) < 5:
        trend = "stable"
    elif seven_day_change > 0:
        trend = "rising"
    else:
        trend = "falling"

    recent_prices = [
        {
            "date": row["arrival_date"].strftime("%Y-%m-%d"),
            "modal_price": safe_float(row["modal_price"])
        }
        for _, row in df.iterrows()
    ]

    return {
        "available": True,
        "source": "AGMARKNET / OGD India",
        "state": str(latest.get("state", "")),
        "district": str(latest.get("district", "")),
        "market": str(latest.get("market", "")),
        "crop": str(latest.get("commodity", "")),
        "price_unit": str(latest.get("price_unit", "Rs./Quintal")),
        "period": {
            "from": first["arrival_date"].strftime("%Y-%m-%d"),
            "to": latest["arrival_date"].strftime("%Y-%m-%d")
        },
        "latest": {
            "date": latest["arrival_date"].strftime("%Y-%m-%d"),
            "min_price": safe_float(latest["min_price"]),
            "max_price": safe_float(latest["max_price"]),
            "modal_price": latest_price
        },
        "seven_day_average_modal_price": round(avg_price, 2),
        "previous_day_modal_price": previous_price,
        "day_over_day_change_percent": (
            round(day_change, 2) if day_change is not None else None
        ),
        "seven_day_change_percent": (
            round(seven_day_change, 2) if seven_day_change is not None else None
        ),
        "trend": trend,
        "recent_modal_prices": recent_prices
    }

In [91]:
def summarize_weather(weather_data: dict) -> dict:
    """
    weather_data is the full JSON dict returned by OpenWeather /forecast.
    It groups 3-hour entries into daily min/max temperatures and max rain chance.
    """
    if not weather_data or weather_data.get("cod") not in ("200", 200):
        return {
            "available": False,
            "message": "Weather forecast is unavailable."
        }

    forecast_df = pd.DataFrame(weather_data.get("list", []))

    if forecast_df.empty:
        return {
            "available": False,
            "message": "Weather forecast contains no entries."
        }

    forecast_df["datetime"] = pd.to_datetime(forecast_df["dt_txt"], errors="coerce")
    forecast_df = forecast_df.dropna(subset=["datetime"]).copy()

    forecast_df["date"] = forecast_df["datetime"].dt.strftime("%Y-%m-%d")
    forecast_df["temp_c"] = forecast_df["main"].apply(
        lambda x: safe_float(x.get("temp")) if isinstance(x, dict) else None
    )
    forecast_df["rain_probability_percent"] = (
        pd.to_numeric(forecast_df.get("pop", 0), errors="coerce")
        .fillna(0)
        .mul(100)
    )
    forecast_df["condition"] = forecast_df["weather"].apply(
        lambda x: x[0].get("description", "unknown")
        if isinstance(x, list) and len(x) > 0 else "unknown"
    )

    forecast_df = forecast_df.dropna(subset=["temp_c"])

    daily = (
        forecast_df.groupby("date", as_index=False)
        .agg(
            min_temp_c=("temp_c", "min"),
            max_temp_c=("temp_c", "max"),
            rain_probability_max_percent=("rain_probability_percent", "max"),
            conditions=("condition", lambda x: ", ".join(sorted(set(x))))
        )
        .head(5)
    )

    daily_forecast = [
        {
            "date": row["date"],
            "min_temp_c": round(safe_float(row["min_temp_c"]), 2),
            "max_temp_c": round(safe_float(row["max_temp_c"]), 2),
            "rain_probability_max_percent": round(
                safe_float(row["rain_probability_max_percent"], 0), 0
            ),
            "conditions": row["conditions"]
        }
        for _, row in daily.iterrows()
    ]

    city = weather_data.get("city", {})
    return {
        "available": True,
        "source": "OpenWeather forecast",
        "location": city.get("name", "Unknown"),
        "latitude": safe_float(city.get("coord", {}).get("lat")),
        "longitude": safe_float(city.get("coord", {}).get("lon")),
        "daily_forecast": daily_forecast
    }

In [97]:
def calculate_rule_engine(market: dict, weather: dict, crop: dict) -> dict:
    facts = []
    reasons = []

    crop_name = crop.get("crop_name", market.get("crop", "This crop"))
    latest_price = market.get("latest", {}).get("modal_price")
    change = market.get("seven_day_change_percent")
    trend = market.get("trend", "unknown")

    max_forecast_temp = None
    max_rain_probability = 0

    if weather.get("available"):
        temperatures = [
            day["max_temp_c"]
            for day in weather.get("daily_forecast", [])
            if day.get("max_temp_c") is not None
        ]

        rain_probs = [
            day.get("rain_probability_max_percent", 0)
            for day in weather.get("daily_forecast", [])
        ]

        max_forecast_temp = max(temperatures) if temperatures else None
        max_rain_probability = max(rain_probs) if rain_probs else 0

    critical_max = crop.get("critical_temp_max_c")
    critical_min = crop.get("critical_temp_min_c")
    storage_life = crop.get("storage_life_days")
    perishability = crop.get("perishability", "unknown")
    sell_bias = crop.get("sell_or_wait_bias", "")
    heat_sensitive = crop.get("heat_sensitive", False)
    rain_sensitive = crop.get("rain_sensitive", False)
    waterlogging_sensitive = crop.get("waterlogging_sensitive", False)

    heat_risk = (
        heat_sensitive
        and max_forecast_temp is not None
        and critical_max is not None
        and max_forecast_temp > critical_max
    )

    rain_risk = (
        max_rain_probability >= 60
        and (rain_sensitive or waterlogging_sensitive)
    )

    cold_risk = False
    min_forecast_temp = None

    if weather.get("available"):
        min_temperatures = [
            day["min_temp_c"]
            for day in weather.get("daily_forecast", [])
            if day.get("min_temp_c") is not None
        ]
        min_forecast_temp = min(min_temperatures) if min_temperatures else None

        cold_risk = (
            min_forecast_temp is not None
            and critical_min is not None
            and min_forecast_temp < critical_min
        )

    if latest_price is not None:
        facts.append(
            f"Latest modal price is Rs.{latest_price:.0f} per quintal."
        )

    if change is not None:
        facts.append(
            f"Seven-day price change is {change:+.2f}% and the trend is {trend}."
        )

    if heat_risk:
        facts.append(
            f"Maximum forecast temperature is {max_forecast_temp:.1f}°C, "
            f"above {crop_name}'s critical maximum of {critical_max:.1f}°C."
        )
        reasons.append(
            f"High temperature may reduce {crop_name} quality or yield."
        )

    if cold_risk:
        facts.append(
            f"Minimum forecast temperature is {min_forecast_temp:.1f}°C, "
            f"below {crop_name}'s critical minimum of {critical_min:.1f}°C."
        )
        reasons.append(
            f"Low temperature may damage {crop_name}."
        )

    if rain_risk:
        facts.append(
            f"Maximum forecast rain probability is {max_rain_probability:.0f}%."
        )
        reasons.append(
            f"Rain may increase harvest, transport, or storage risk for {crop_name}."
        )

    if perishability == "high":
        reasons.append(f"{crop_name} is highly perishable.")
    elif perishability == "medium":
        reasons.append(f"{crop_name} has moderate storage limitations.")

    # Generic, explainable decision policy
    if heat_risk or cold_risk or rain_risk:
        decision = "sell_within_1_to_3_days"

    elif sell_bias == "sell_fast_if_perishable" and trend == "falling":
        decision = "sell_soon"

    elif (
        trend == "rising"
        and storage_life is not None
        and storage_life >= 7
        and perishability != "high"
    ):
        decision = "monitor_for_1_day_before_selling"

    else:
        decision = "sell_soon"

    return {
        "recommended_decision": decision,
        "market_signal": trend,
        "weather_risk": {
            "heat_risk": heat_risk,
            "cold_risk": cold_risk,
            "rain_risk": rain_risk,
            "max_forecast_temp_c": max_forecast_temp,
            "min_forecast_temp_c": min_forecast_temp,
            "max_rain_probability_percent": max_rain_probability
        },
        "crop_storage_signal": perishability,
        "facts_for_explanation": facts,
        "reasons": reasons
    }

In [98]:
def prepare_gemma_payload(history, weather_data, crop_data, language="Telugu") -> dict:
    market_summary = summarize_market(history)
    weather_summary = summarize_weather(weather_data)
    rule_engine_result = calculate_rule_engine(
        market_summary,
        weather_summary,
        crop_data
    )

    return {
        "farmer_context": {
            "language": language,
            "state": market_summary.get("state"),
            "district": market_summary.get("district"),
            "market": market_summary.get("market"),
            "crop": market_summary.get("crop"),
            "weather_location": weather_summary.get("location")
        },
        "market_summary": market_summary,
        "weather_summary": weather_summary,
        "crop_knowledge": crop_data,
        "rule_engine_result": rule_engine_result
    }

In [99]:
gemma_payload = prepare_gemma_payload(
    history=historic_prices,
    weather_data=data_weather,
    crop_data=crop_knowledge,
    language="Telugu"
)

print(json.dumps(gemma_payload, indent=2, ensure_ascii=False))

{
  "farmer_context": {
    "language": "Telugu",
    "state": "Andhra Pradesh",
    "district": "Chittor",
    "market": "Palamaner APMC",
    "crop": "Potato",
    "weather_location": "Madanapalle"
  },
  "market_summary": {
    "available": true,
    "source": "AGMARKNET / OGD India",
    "state": "Andhra Pradesh",
    "district": "Chittor",
    "market": "Palamaner APMC",
    "crop": "Potato",
    "price_unit": "Rs./Quintal",
    "period": {
      "from": "2026-07-04",
      "to": "2026-07-10"
    },
    "latest": {
      "date": "2026-07-10",
      "min_price": 1400.0,
      "max_price": 2000.0,
      "modal_price": 1600.0
    },
    "seven_day_average_modal_price": 1628.57,
    "previous_day_modal_price": 1600.0,
    "day_over_day_change_percent": 0.0,
    "seven_day_change_percent": -11.11,
    "trend": "falling",
    "recent_modal_prices": [
      {
        "date": "2026-07-04",
        "modal_price": 1800.0
      },
      {
        "date": "2026-07-05",
        "modal_price": 1600.0
      },
      {
        "date": "2026-07-06",
        "modal_price": 1600.0
      },
      {
        "date": "2026-07-07",
        "modal_price": 1600.0
      },
      {
        "date": "2026-07-08",
        "modal_price": 1600.0
      },
      {
        "date": "2026-07-09",
        "modal_price": 1600.0
      },
      {
        "date": "2026-07-10",
        "modal_price": 1600.0
      }
    ]
  },
  "weather_summary": {
    "available": true,
    "source": "OpenWeather forecast",
    "location": "Madanapalle",
    "latitude": 13.552,
    "longitude": 78.5058,
    "daily_forecast": [
      {
        "date": "2026-07-10",
        "min_temp_c": 23.73,
        "max_temp_c": 28.97,
        "rain_probability_max_percent": 0.0,
        "conditions": "overcast clouds"
      },
      {
        "date": "2026-07-11",
        "min_temp_c": 22.68,
        "max_temp_c": 31.23,
        "rain_probability_max_percent": 0.0,
        "conditions": "overcast clouds"
      },
      {
        "date": "2026-07-12",
        "min_temp_c": 22.76,
        "max_temp_c": 32.38,
        "rain_probability_max_percent": 0.0,
        "conditions": "overcast clouds"
      },
      {
        "date": "2026-07-13",
        "min_temp_c": 22.46,
        "max_temp_c": 33.74,
        "rain_probability_max_percent": 0.0,
        "conditions": "overcast clouds"
      },
      {
        "date": "2026-07-14",
        "min_temp_c": 22.14,
        "max_temp_c": 29.88,
        "rain_probability_max_percent": 0.0,
        "conditions": "overcast clouds"
      }
    ]
  },
  "crop_knowledge": {
    "crop_name": "Potato",
    "optimal_temp_range_c": [
      15,
      20
    ],
    "critical_temp_max_c": 26.6,
    "critical_temp_min_c": 2,
    "chilling_injury_threshold_c": null,
    "frost_sensitive": true,
    "heat_sensitive": false,
    "rain_sensitive": true,
    "waterlogging_sensitive": true,
    "rain_risk_mm_threshold": 20,
    "storage_life_days": 180,
    "storage_temp_by_use_c": {
      "seed": [
        2.0,
        4.0
      ],
      "table_fresh": [
        4.0,
        7.0
      ],
      "processing_chips_fries": [
        8.0,
        10.0
      ]
    },
    "perishability": "medium",
    "harvest_window_days": 7,
    "field_lifecycle_days": [
      90,
      120
    ],
    "price_volatility": "medium",
    "sell_or_wait_bias": "can_wait_for_better_price",
    "grading_note": "Grades: Super, Grade-A, Grade-B. Large/Super: over 65mm diameter. Medium/Grade A: 46-65mm. Small/Grade B: 35-45mm. Processing buyers require 20-25% dry matter content; low dry matter causes excess oil absorption and disintegration when fried.",
    "advisory_note": "Storage temperature determines end-use suitability: table potatoes stored at 4-7C develop cold-induced sweetening (starch converts to sugar) and are unsuitable for processing/frying, which requires warmer 8-10C storage to avoid dark, bitter fries. Do not advise selling cold-stored table potatoes to processing buyers during a price crash in the table market; they will likely be rejected at the processing gate. Table potatoes have roughly a 6-month shelf life, so holding until the table market recovers is often viable. Rain and cool, humid conditions favor late blight; waterlogging during tuber initiation (35-45 days) or bulking (60-75 days) is especially damaging."
  },
  "rule_engine_result": {
    "recommended_decision": "sell_soon",
    "market_signal": "falling",
    "weather_risk": {
      "heat_risk": false,
      "cold_risk": false,
      "rain_risk": false,
      "max_forecast_temp_c": 33.74,
      "min_forecast_temp_c": 22.14,
      "max_rain_probability_percent": 0.0
    },
    "crop_storage_signal": "medium",
    "facts_for_explanation": [
      "Latest modal price is Rs.1600 per quintal.",
      "Seven-day price change is -11.11% and the trend is falling."
    ],
    "reasons": [
      "Potato has moderate storage limitations."
    ]
  }
}

In [100]:
pprint.pp(gemma_payload)

{'farmer_context': {'language': 'Telugu',
                    'state': 'Andhra Pradesh',
                    'district': 'Chittor',
                    'market': 'Palamaner APMC',
                    'crop': 'Potato',
                    'weather_location': 'Madanapalle'},
 'market_summary': {'available': True,
                    'source': 'AGMARKNET / OGD India',
                    'state': 'Andhra Pradesh',
                    'district': 'Chittor',
                    'market': 'Palamaner APMC',
                    'crop': 'Potato',
                    'price_unit': 'Rs./Quintal',
                    'period': {'from': '2026-07-04', 'to': '2026-07-10'},
                    'latest': {'date': '2026-07-10',
                               'min_price': 1400.0,
                               'max_price': 2000.0,
                               'modal_price': 1600.0},
                    'seven_day_average_modal_price': 1628.57,
                    'previous_day_modal_price': 1600.0,
                    'day_over_day_change_percent': 0.0,
                    'seven_day_change_percent': -11.11,
                    'trend': 'falling',
                    'recent_modal_prices': [{'date': '2026-07-04',
                                             'modal_price': 1800.0},
                                            {'date': '2026-07-05',
                                             'modal_price': 1600.0},
                                            {'date': '2026-07-06',
                                             'modal_price': 1600.0},
                                            {'date': '2026-07-07',
                                             'modal_price': 1600.0},
                                            {'date': '2026-07-08',
                                             'modal_price': 1600.0},
                                            {'date': '2026-07-09',
                                             'modal_price': 1600.0},
                                            {'date': '2026-07-10',
                                             'modal_price': 1600.0}]},
 'weather_summary': {'available': True,
                     'source': 'OpenWeather forecast',
                     'location': 'Madanapalle',
                     'latitude': 13.552,
                     'longitude': 78.5058,
                     'daily_forecast': [{'date': '2026-07-10',
                                         'min_temp_c': 23.73,
                                         'max_temp_c': 28.97,
                                         'rain_probability_max_percent': 0.0,
                                         'conditions': 'overcast clouds'},
                                        {'date': '2026-07-11',
                                         'min_temp_c': 22.68,
                                         'max_temp_c': 31.23,
                                         'rain_probability_max_percent': 0.0,
                                         'conditions': 'overcast clouds'},
                                        {'date': '2026-07-12',
                                         'min_temp_c': 22.76,
                                         'max_temp_c': 32.38,
                                         'rain_probability_max_percent': 0.0,
                                         'conditions': 'overcast clouds'},
                                        {'date': '2026-07-13',
                                         'min_temp_c': 22.46,
                                         'max_temp_c': 33.74,
                                         'rain_probability_max_percent': 0.0,
                                         'conditions': 'overcast clouds'},
                                        {'date': '2026-07-14',
                                         'min_temp_c': 22.14,
                                         'max_temp_c': 29.88,
                                         'rain_probability_max_percent': 0.0,
                                         'conditions': 'overcast clouds'}]},
 'crop_knowledge': {'crop_name': 'Potato',
                    'optimal_temp_range_c': [15, 20],
                    'critical_temp_max_c': 26.6,
                    'critical_temp_min_c': 2,
                    'chilling_injury_threshold_c': None,
                    'frost_sensitive': True,
                    'heat_sensitive': False,
                    'rain_sensitive': True,
                    'waterlogging_sensitive': True,
                    'rain_risk_mm_threshold': 20,
                    'storage_life_days': 180,
                    'storage_temp_by_use_c': {'seed': [2.0, 4.0],
                                              'table_fresh': [4.0, 7.0],
                                              'processing_chips_fries': [8.0,
                                                                         10.0]},
                    'perishability': 'medium',
                    'harvest_window_days': 7,
                    'field_lifecycle_days': [90, 120],
                    'price_volatility': 'medium',
                    'sell_or_wait_bias': 'can_wait_for_better_price',
                    'grading_note': 'Grades: Super, Grade-A, Grade-B. '
                                    'Large/Super: over 65mm diameter. '
                                    'Medium/Grade A: 46-65mm. Small/Grade B: '
                                    '35-45mm. Processing buyers require 20-25% '
                                    'dry matter content; low dry matter causes '
                                    'excess oil absorption and disintegration '
                                    'when fried.',
                    'advisory_note': 'Storage temperature determines end-use '
                                     'suitability: table potatoes stored at '
                                     '4-7C develop cold-induced sweetening '
                                     '(starch converts to sugar) and are '
                                     'unsuitable for processing/frying, which '
                                     'requires warmer 8-10C storage to avoid '
                                     'dark, bitter fries. Do not advise '
                                     'selling cold-stored table potatoes to '
                                     'processing buyers during a price crash '
                                     'in the table market; they will likely be '
                                     'rejected at the processing gate. Table '
                                     'potatoes have roughly a 6-month shelf '
                                     'life, so holding until the table market '
                                     'recovers is often viable. Rain and cool, '
                                     'humid conditions favor late blight; '
                                     'waterlogging during tuber initiation '
                                     '(35-45 days) or bulking (60-75 days) is '
                                     'especially damaging.'},
 'rule_engine_result': {'recommended_decision': 'sell_soon',
                        'market_signal': 'falling',
                        'weather_risk': {'heat_risk': False,
                                         'cold_risk': False,
                                         'rain_risk': False,
                                         'max_forecast_temp_c': 33.74,
                                         'min_forecast_temp_c': 22.14,
                                         'max_rain_probability_percent': 0.0},
                        'crop_storage_signal': 'medium',
                        'facts_for_explanation': ['Latest modal price is '
                                                  'Rs.1600 per quintal.',
                                                  'Seven-day price change is '
                                                  '-11.11% and the trend is '
                                                  'falling.'],
                        'reasons': ['Potato has moderate storage '
                                    'limitations.']}}

In [96]:
len(str(gemma_payload))

4005

In [103]:
historic_prices = fetch_historical_prices(commodity='Green Chilli', state='Andhra Pradesh')

In [104]:
historic_prices

,arrival_date,state,district,market,commodity_group,commodity,variety,grade,min_price,max_price,modal_price,price_unit,arrival_quantity,arrival_unit
0,2026-07-04,Andhra Pradesh,Chittor,Palamaner APMC,Vegetables,Green Chilli,Green Chilly,FAQ,3000.0,4000.0,3500.0,Rs./Quintal,2.7,Metric Tonnes
1,2026-07-05,Andhra Pradesh,Chittor,Palamaner APMC,Vegetables,Green Chilli,Green Chilly,FAQ,3000.0,4000.0,3500.0,Rs./Quintal,2.2,Metric Tonnes
2,2026-07-06,Andhra Pradesh,Chittor,Palamaner APMC,Vegetables,Green Chilli,Green Chilly,FAQ,3000.0,4000.0,3500.0,Rs./Quintal,2.4,Metric Tonnes
3,2026-07-07,Andhra Pradesh,Chittor,Palamaner APMC,Vegetables,Green Chilli,Green Chilly,FAQ,3000.0,4000.0,3500.0,Rs./Quintal,2.7,Metric Tonnes
4,2026-07-08,Andhra Pradesh,Chittor,Palamaner APMC,Vegetables,Green Chilli,Green Chilly,FAQ,3000.0,4000.0,3500.0,Rs./Quintal,2.2,Metric Tonnes
5,2026-07-09,Andhra Pradesh,Chittor,Palamaner APMC,Vegetables,Green Chilli,Green Chilly,FAQ,3000.0,4000.0,3500.0,Rs./Quintal,NaN,None
6,2026-07-10,Andhra Pradesh,Chittor,Palamaner APMC,Vegetables,Green Chilli,Green Chilly,FAQ,3000.0,4000.0,3500.0,Rs./Quintal,NaN,None

In [106]:
import json
import pprint
commodity = 'Green Chilli'
file_path = r"../crop_database/crop_knowledge_base.json"

with open(file_path, "r", encoding="utf-8") as file:
    data = json.load(file)

print(pprint.pp(data[f'{commodity.lower()}']))

crop_knowledge = data[f'{commodity.lower()}']

{'crop_name': 'Green Chilli',
 'optimal_temp_range_c': [20, 30],
 'critical_temp_max_c': 35,
 'critical_temp_min_c': 5,
 'chilling_injury_threshold_c': 5,
 'frost_sensitive': True,
 'heat_sensitive': True,
 'rain_sensitive': True,
 'waterlogging_sensitive': True,
 'rain_risk_mm_threshold': 20,
 'storage_life_days': 21,
 'storage_temp_range_c': [7, 10],
 'perishability': 'high',
 'harvest_window_days': 5,
 'field_lifecycle_days': [90, 120],
 'price_volatility': 'high',
 'sell_or_wait_bias': 'sell_fast_if_perishable',
 'grading_note': 'Graded by size uniformity, color intensity, shape, and '
                 'pungency. Grade A export chillies (uniform, bright green, '
                 'unblemished) fetch Rs.60-90/kg vs Rs.38-55/kg for standard '
                 'domestic quality. Popular export varieties: G4 (UAE/UK/USA, '
                 'long shelf life), Bullet (Middle East/Europe retail), '
                 'Jwala/Teja (South/Southeast Asia, high pungency).',
 'advisory_note': 'Green chillies degrade within 3-5 days at ambient '
                  'temperature, 2-3 weeks under normal refrigeration, but can '
                  'last up to 45 days under strict export cold chain (7-10C, '
                  '90-95% humidity). Storage below 5C causes irreversible '
                  'chilling injury: water-soaked spots, tissue softening, '
                  'pitting, and rapid fungal decay upon warming. Erratic '
                  'watering (drought followed by waterlogging) causes blossom '
                  'end rot, a black necrotic lesion at the fruit base that '
                  'makes chillies unsaleable. Do not wash chillies before '
                  'storage, as this accelerates microbial decay.'}
None

In [107]:
gemma_payload = prepare_gemma_payload(
    history=historic_prices,
    weather_data=data_weather,
    crop_data=crop_knowledge,
    language="Telugu"
)

print(json.dumps(gemma_payload, indent=2, ensure_ascii=False))

{
  "farmer_context": {
    "language": "Telugu",
    "state": "Andhra Pradesh",
    "district": "Chittor",
    "market": "Palamaner APMC",
    "crop": "Green Chilli",
    "weather_location": "Madanapalle"
  },
  "market_summary": {
    "available": true,
    "source": "AGMARKNET / OGD India",
    "state": "Andhra Pradesh",
    "district": "Chittor",
    "market": "Palamaner APMC",
    "crop": "Green Chilli",
    "price_unit": "Rs./Quintal",
    "period": {
      "from": "2026-07-04",
      "to": "2026-07-10"
    },
    "latest": {
      "date": "2026-07-10",
      "min_price": 3000.0,
      "max_price": 4000.0,
      "modal_price": 3500.0
    },
    "seven_day_average_modal_price": 3500.0,
    "previous_day_modal_price": 3500.0,
    "day_over_day_change_percent": 0.0,
    "seven_day_change_percent": 0.0,
    "trend": "stable",
    "recent_modal_prices": [
      {
        "date": "2026-07-04",
        "modal_price": 3500.0
      },
      {
        "date": "2026-07-05",
        "modal_price": 3500.0
      },
      {
        "date": "2026-07-06",
        "modal_price": 3500.0
      },
      {
        "date": "2026-07-07",
        "modal_price": 3500.0
      },
      {
        "date": "2026-07-08",
        "modal_price": 3500.0
      },
      {
        "date": "2026-07-09",
        "modal_price": 3500.0
      },
      {
        "date": "2026-07-10",
        "modal_price": 3500.0
      }
    ]
  },
  "weather_summary": {
    "available": true,
    "source": "OpenWeather forecast",
    "location": "Madanapalle",
    "latitude": 13.552,
    "longitude": 78.5058,
    "daily_forecast": [
      {
        "date": "2026-07-10",
        "min_temp_c": 23.73,
        "max_temp_c": 28.97,
        "rain_probability_max_percent": 0.0,
        "conditions": "overcast clouds"
      },
      {
        "date": "2026-07-11",
        "min_temp_c": 22.68,
        "max_temp_c": 31.23,
        "rain_probability_max_percent": 0.0,
        "conditions": "overcast clouds"
      },
      {
        "date": "2026-07-12",
        "min_temp_c": 22.76,
        "max_temp_c": 32.38,
        "rain_probability_max_percent": 0.0,
        "conditions": "overcast clouds"
      },
      {
        "date": "2026-07-13",
        "min_temp_c": 22.46,
        "max_temp_c": 33.74,
        "rain_probability_max_percent": 0.0,
        "conditions": "overcast clouds"
      },
      {
        "date": "2026-07-14",
        "min_temp_c": 22.14,
        "max_temp_c": 29.88,
        "rain_probability_max_percent": 0.0,
        "conditions": "overcast clouds"
      }
    ]
  },
  "crop_knowledge": {
    "crop_name": "Green Chilli",
    "optimal_temp_range_c": [
      20,
      30
    ],
    "critical_temp_max_c": 35,
    "critical_temp_min_c": 5,
    "chilling_injury_threshold_c": 5,
    "frost_sensitive": true,
    "heat_sensitive": true,
    "rain_sensitive": true,
    "waterlogging_sensitive": true,
    "rain_risk_mm_threshold": 20,
    "storage_life_days": 21,
    "storage_temp_range_c": [
      7,
      10
    ],
    "perishability": "high",
    "harvest_window_days": 5,
    "field_lifecycle_days": [
      90,
      120
    ],
    "price_volatility": "high",
    "sell_or_wait_bias": "sell_fast_if_perishable",
    "grading_note": "Graded by size uniformity, color intensity, shape, and pungency. Grade A export chillies (uniform, bright green, unblemished) fetch Rs.60-90/kg vs Rs.38-55/kg for standard domestic quality. Popular export varieties: G4 (UAE/UK/USA, long shelf life), Bullet (Middle East/Europe retail), Jwala/Teja (South/Southeast Asia, high pungency).",
    "advisory_note": "Green chillies degrade within 3-5 days at ambient temperature, 2-3 weeks under normal refrigeration, but can last up to 45 days under strict export cold chain (7-10C, 90-95% humidity). Storage below 5C causes irreversible chilling injury: water-soaked spots, tissue softening, pitting, and rapid fungal decay upon warming. Erratic watering (drought followed by waterlogging) causes blossom end rot, a black necrotic lesion at the fruit base that makes chillies unsaleable. Do not wash chillies before storage, as this accelerates microbial decay."
  },
  "rule_engine_result": {
    "recommended_decision": "sell_soon",
    "market_signal": "stable",
    "weather_risk": {
      "heat_risk": false,
      "cold_risk": false,
      "rain_risk": false,
      "max_forecast_temp_c": 33.74,
      "min_forecast_temp_c": 22.14,
      "max_rain_probability_percent": 0.0
    },
    "crop_storage_signal": "high",
    "facts_for_explanation": [
      "Latest modal price is Rs.3500 per quintal.",
      "Seven-day price change is +0.00% and the trend is stable."
    ],
    "reasons": [
      "Green Chilli is highly perishable."
    ]
  }
}

In [108]:
pprint.pp(gemma_payload)

{'farmer_context': {'language': 'Telugu',
                    'state': 'Andhra Pradesh',
                    'district': 'Chittor',
                    'market': 'Palamaner APMC',
                    'crop': 'Green Chilli',
                    'weather_location': 'Madanapalle'},
 'market_summary': {'available': True,
                    'source': 'AGMARKNET / OGD India',
                    'state': 'Andhra Pradesh',
                    'district': 'Chittor',
                    'market': 'Palamaner APMC',
                    'crop': 'Green Chilli',
                    'price_unit': 'Rs./Quintal',
                    'period': {'from': '2026-07-04', 'to': '2026-07-10'},
                    'latest': {'date': '2026-07-10',
                               'min_price': 3000.0,
                               'max_price': 4000.0,
                               'modal_price': 3500.0},
                    'seven_day_average_modal_price': 3500.0,
                    'previous_day_modal_price': 3500.0,
                    'day_over_day_change_percent': 0.0,
                    'seven_day_change_percent': 0.0,
                    'trend': 'stable',
                    'recent_modal_prices': [{'date': '2026-07-04',
                                             'modal_price': 3500.0},
                                            {'date': '2026-07-05',
                                             'modal_price': 3500.0},
                                            {'date': '2026-07-06',
                                             'modal_price': 3500.0},
                                            {'date': '2026-07-07',
                                             'modal_price': 3500.0},
                                            {'date': '2026-07-08',
                                             'modal_price': 3500.0},
                                            {'date': '2026-07-09',
                                             'modal_price': 3500.0},
                                            {'date': '2026-07-10',
                                             'modal_price': 3500.0}]},
 'weather_summary': {'available': True,
                     'source': 'OpenWeather forecast',
                     'location': 'Madanapalle',
                     'latitude': 13.552,
                     'longitude': 78.5058,
                     'daily_forecast': [{'date': '2026-07-10',
                                         'min_temp_c': 23.73,
                                         'max_temp_c': 28.97,
                                         'rain_probability_max_percent': 0.0,
                                         'conditions': 'overcast clouds'},
                                        {'date': '2026-07-11',
                                         'min_temp_c': 22.68,
                                         'max_temp_c': 31.23,
                                         'rain_probability_max_percent': 0.0,
                                         'conditions': 'overcast clouds'},
                                        {'date': '2026-07-12',
                                         'min_temp_c': 22.76,
                                         'max_temp_c': 32.38,
                                         'rain_probability_max_percent': 0.0,
                                         'conditions': 'overcast clouds'},
                                        {'date': '2026-07-13',
                                         'min_temp_c': 22.46,
                                         'max_temp_c': 33.74,
                                         'rain_probability_max_percent': 0.0,
                                         'conditions': 'overcast clouds'},
                                        {'date': '2026-07-14',
                                         'min_temp_c': 22.14,
                                         'max_temp_c': 29.88,
                                         'rain_probability_max_percent': 0.0,
                                         'conditions': 'overcast clouds'}]},
 'crop_knowledge': {'crop_name': 'Green Chilli',
                    'optimal_temp_range_c': [20, 30],
                    'critical_temp_max_c': 35,
                    'critical_temp_min_c': 5,
                    'chilling_injury_threshold_c': 5,
                    'frost_sensitive': True,
                    'heat_sensitive': True,
                    'rain_sensitive': True,
                    'waterlogging_sensitive': True,
                    'rain_risk_mm_threshold': 20,
                    'storage_life_days': 21,
                    'storage_temp_range_c': [7, 10],
                    'perishability': 'high',
                    'harvest_window_days': 5,
                    'field_lifecycle_days': [90, 120],
                    'price_volatility': 'high',
                    'sell_or_wait_bias': 'sell_fast_if_perishable',
                    'grading_note': 'Graded by size uniformity, color '
                                    'intensity, shape, and pungency. Grade A '
                                    'export chillies (uniform, bright green, '
                                    'unblemished) fetch Rs.60-90/kg vs '
                                    'Rs.38-55/kg for standard domestic '
                                    'quality. Popular export varieties: G4 '
                                    '(UAE/UK/USA, long shelf life), Bullet '
                                    '(Middle East/Europe retail), Jwala/Teja '
                                    '(South/Southeast Asia, high pungency).',
                    'advisory_note': 'Green chillies degrade within 3-5 days '
                                     'at ambient temperature, 2-3 weeks under '
                                     'normal refrigeration, but can last up to '
                                     '45 days under strict export cold chain '
                                     '(7-10C, 90-95% humidity). Storage below '
                                     '5C causes irreversible chilling injury: '
                                     'water-soaked spots, tissue softening, '
                                     'pitting, and rapid fungal decay upon '
                                     'warming. Erratic watering (drought '
                                     'followed by waterlogging) causes blossom '
                                     'end rot, a black necrotic lesion at the '
                                     'fruit base that makes chillies '
                                     'unsaleable. Do not wash chillies before '
                                     'storage, as this accelerates microbial '
                                     'decay.'},
 'rule_engine_result': {'recommended_decision': 'sell_soon',
                        'market_signal': 'stable',
                        'weather_risk': {'heat_risk': False,
                                         'cold_risk': False,
                                         'rain_risk': False,
                                         'max_forecast_temp_c': 33.74,
                                         'min_forecast_temp_c': 22.14,
                                         'max_rain_probability_percent': 0.0},
                        'crop_storage_signal': 'high',
                        'facts_for_explanation': ['Latest modal price is '
                                                  'Rs.3500 per quintal.',
                                                  'Seven-day price change is '
                                                  '+0.00% and the trend is '
                                                  'stable.'],
                        'reasons': ['Green Chilli is highly perishable.']}}

In [113]:
def make_fast_payload(gemma_payload):
    market = gemma_payload["market_summary"]
    weather = gemma_payload["weather_summary"]
    crop = gemma_payload["crop_knowledge"]
    rules = gemma_payload["rule_engine_result"]
    farmer = gemma_payload["farmer_context"]

    return {
        "lang": farmer["language"],
        "crop": farmer["crop"],
        "market": farmer["market"],
        "district": farmer["district"],
        "decision": rules["recommended_decision"],
        "price": round(market["latest"]["modal_price"]),
        "chg7d_pct": round(market["seven_day_change_percent"], 1),
        "trend": market["trend"],
        "max_temp_c": round(rules["weather_risk"]["max_forecast_temp_c"]),
        "heat_risk": rules["weather_risk"]["heat_risk"],
        "rain_risk": rules["weather_risk"]["rain_risk"],
        "perishable": crop["perishability"],
        "storage_days": crop["storage_life_days"],
        "crit_temp_c": crop["critical_temp_max_c"],
        "reasons": rules["reasons"],  # cap to top 2, see point 3
    }

In [114]:
make_fast_payload(gemma_payload)

{'lang': 'Telugu',
 'crop': 'Green Chilli',
 'market': 'Palamaner APMC',
 'district': 'Chittor',
 'decision': 'sell_soon',
 'price': 3500,
 'chg7d_pct': 0.0,
 'trend': 'stable',
 'max_temp_c': 34,
 'heat_risk': False,
 'rain_risk': False,
 'perishable': 'high',
 'storage_days': 21,
 'crit_temp_c': 35,
 'reasons': ['Green Chilli is highly perishable.']}

In [115]:
def payload_to_prompt(p):
    return (
        f"Crop:{p['crop']} Market:{p['market']},{p['district']} Lang:{p['lang']}\n"
        f"Price:{p['price']}/quintal Chg7d:{p['chg7d_pct']}% Trend:{p['trend']}\n"
        f"MaxTemp:{p['max_temp_c']}C HeatRisk:{p['heat_risk']} RainRisk:{p['rain_risk']}\n"
        f"Perishable:{p['perishable']} StorageDays:{p['storage_days']} CritTemp:{p['crit_temp_c']}\n"
        f"Reasons:{'; '.join(p['reasons'])}\n"
        f"Decision so far:{p['decision']}"
    )

In [116]:
payload_to_prompt(make_fast_payload(gemma_payload))

'Crop:Green Chilli Market:Palamaner APMC,Chittor Lang:Telugu\nPrice:3500/quintal Chg7d:0.0% Trend:stable\nMaxTemp:34C HeatRisk:False RainRisk:False\nPerishable:high StorageDays:21 CritTemp:35\nReasons:Green Chilli is highly perishable.\nDecision so far:sell_soon'